services:
  shortlink-mysql:
    image: mysql:8.0
    container_name: shortlink-mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql    # ← 命名卷，Linux 文件系统
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shortlink_db

  shortlink-redis:
    image: redis:7-alpine
    container_name: shortlink-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass 123456

  shortlink-app:
    build: .
    container_name: shortlink-app
    ports:
      - "8080:8080"
    depends_on:
      - shortlink-mysql
      - shortlink-redis

volumes:
  mysql_data:                         # ← 声明命名卷
  redis_data: