spring.application.name=shortlink-core

# MySQL配置
spring.datasource.url=jdbc:mysql://shortlink-mysql:3306/shortlink_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA配置
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

shortlink.base-url=http://localhost:8080/

# Redis配置
spring.data.redis.host=shortlink-redis
spring.data.redis.port=6379
spring.data.redis.password=123456

# 缓存过期时间（秒），短链缓存 1 小时
shortlink.cache.ttl=3600
